### ISSUE TITLE
Create anaconda and docker accounts

### ISSUE THREAD

**Issue by bananabenana** [kelwyres/Bactabolize#18]
Create Anaconda account (https://anaconda.org/scwatts/dashboard) and a Docker account (https://hub.docker.com/signup) for the Bactabolize Conda package and Docker image. 

Currently sourced from scwatts anaconda

**Comment by scwatts** [comment]
You'll also need to create access tokens and store in a secure place, then set the corresponding GitHub Actions secrets to enable automatic upload of the build artefacts.
