### ISSUE TITLE
bactabolize installation

### ISSUE THREAD

**Issue by microbial-cookie** [kelwyres/Bactabolize#23]
Hi developers, 

Recently, I have installed the bactabolize, but I run this command bactabolize -h, something wrong happened,

ImportError: cannot import name 'open_text' from 'importlib_resources' (/auto/sahara/namib/home/ruiwenhu/mambaforge/envs/bactabolize/lib/python3.9/site-packa

Please help me to solve this problem, thanks!

**Comment by bananabenana** [comment]
Hi @microbial-cookie,

Please paste the full error message. My assumption right now is you may need to install that package:

```
conda activate bactabolize
pip install importlib-resources
```
If this doesn't resolve this, please paste here:

1. The complete error message
2. Commands used to install and any associated error messages
3. Also, once activating your environment, try `conda list`.


Thanks

**Comment by microbial-cookie** [comment]
Hi developers,

attachments of the complete error message is below:  

![35161696311391_ pic](https://github.com/kelwyres/Bactabolize/assets/133230591/a06aeb91-52f3-4a47-b4c0-27a0cf9cc369)
![35171696311440_ pic](https://github.com/kelwyres/Bactabolize/assets/133230591/cb75c312-5a40-46ff-aae0-8601a8e83d74)
![35181696311484_ pic](https://github.com/kelwyres/Bactabolize/assets/133230591/6734eaa7-b0c9-42e5-b963-a306b89e1fd1)

**Comment by rebeccajhall** [comment]
Hi all, I'm getting the same error (same error message and requirement for importlib-resources already satisfied).

Thanks,
Rebecca

**Comment by bananabenana** [comment]
Hi @rebeccajhall and @microbial-cookie microbial,

Thank you for those details.
I can confirm the issue is with a newer importlib_resources version.

I will push an update in the next few days to ensure the previous version is used for auto install. In the meantime, to get this running, could you please run the following:

```
# Create and activate environment via mamba
mamba create -n bactabolize_1.0.1 -y -c scwatts -c bioconda -c conda-forge 'bactabolize==1.0.1'
mamba install -n bactabolize_1.0.1 -y -c conda-forge importlib_resources=5.12.0 # this is a downgrade from the current version 6 which gets installed.
conda activate bactabolize_1.0.1


# Test installation
bactabolize -h

```

Hopefully this will fix the problem. Let me know if there's still an issue.

**Comment by bananabenana** [comment]
This has now been bugfixed in version 1.0.2 https://github.com/kelwyres/Bactabolize/releases/tag/1.0.2

For future readers, install with: 
`mamba create -n bactabolize -y -c scwatts -c bioconda -c conda-forge 'bactabolize==1.0.2'`

Please reopen this issue if this does not solve the problem for you.
