### ISSUE TITLE
Unable to Install bactabolize==1.0.2 Due to Missing blast 2.12.0 Dependency

### ISSUE THREAD

**Issue by YahyaFarooqi** [kelwyres/Bactabolize#24]
While trying to create a new environment and install bactabolize==1.0.2 using Mamba, I encountered an issue stating that the package could not be installed due to a missing blast 2.12.0 dependency.

I'm running:

```
mamba create -n bactabolize -y -c scwatts -c bioconda -c conda-forge 'bactabolize==1.0.2'
```

And I get:

> Looking for: ['bactabolize==1.0.2']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/main/osx-arm64                                           No change
bioconda/noarch                                               No change
bioconda/osx-arm64                                            No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/r/osx-arm64                                              No change
scwatts/osx-arm64                                             No change
scwatts/noarch                                                No change
Could not solve for environment specs
The following package could not be installed
└─ bactabolize 1.0.2  is not installable because it requires
   └─ blast 2.12.0 , which does not exist (perhaps a missing channel).
(base) user@M4819 Bactabolize % 

Any help would be appreciated. I'm running on mac M1.

**Comment by bananabenana** [comment]
Hi @YahyaFarooqi 

That is strange as Blast 2.12.0 is part of the conda recipe.
I am not able to replicate this issue on two independent Linux systems. When running the following command I get a clean install:

```bash
# Create and activate environment via mamba
mamba create -n bactabolize -y -c scwatts -c bioconda -c conda-forge 'bactabolize==1.0.2'
conda activate bactabolize

# Test installation
bactabolize -h

```

If this isn't working for you, maybe try to conda install blast prior.
```bash
mamba create -n bactabolize -y
mamba install -n bactabolize -y -c bioconda blast=2.12.0
mamba install -n bactabolize_test_1.0.2 -y -c scwatts -c bioconda -c conda-forge 'bactabolize==1.0.2'
```

Let us know if this fixes the issue.
Thanks

**Comment by jotech** [comment]
i think the issue is related to the missing arm64 support of bioconda!
but there seems to be some progress in the recent weeks: https://github.com/bioconda/bioconda-recipes/issues/23454

**Comment by YahyaFarooqi** [comment]
@jotech that's probably it i suppose?

@bananabenana here is the output I get when I try your suggestion:

> (base) nfarooqi@M4819 ~ % mamba create -n bactabolize -y


Looking for: []

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate bactabolize

To deactivate an active environment, use

     $ mamba deactivate

(base) nfarooqi@M4819 ~ % mamba install -n bactabolize -y -c bioconda blast=2.12.0


Looking for: ['blast=2.12.0']

pkgs/r/osx-arm64                                              No change
bioconda/osx-arm64                                            No change
pkgs/main/osx-arm64                                           No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
conda-forge/noarch                                  12.4MB @  13.4MB/s  0.8s
conda-forge/osx-arm64                                7.2MB @   7.6MB/s  0.8s
bioconda/noarch                                      4.7MB @   3.8MB/s  1.3s
Could not solve for environment specs
The following package could not be installed
└─ blast 2.12.0**  does not exist (perhaps a typo or a missing channel).
(base) nfarooqi@M4819 ~ % 


Any chance for a workaround? Maybe through a local install of blast?

**Comment by bananabenana** [comment]
You can just clone the repo as per our wiki, then install dependancies without conda: https://github.com/kelwyres/Bactabolize/wiki/2.-Installation#direct-install

So local versions of required dependancies, making sure they're available on your path.

**Comment by YahyaFarooqi** [comment]
Thanks for the suggesting, cloning worked!

**Comment by YahyaFarooqi** [comment]
Thanks for the suggestion, cloning worked!
