### ISSUE TITLE
Add helper scripts

### ISSUE THREAD

**Issue by kelwyres** [kelwyres/Bactabolize#7]
Add helper scripts to repo and links as appropriate on wiki
E.g. draft model page needs link to the model converter script
FBA page will need link to combine FBA script

**Comment by bananabenana** [comment]
- Combine FBA reports script
- Convert to BiGG model for Bactabolize script
- Network output script?

**Comment by bananabenana** [comment]
Resolved with [ceb90cb](https://github.com/kelwyres/Bactabolize/commit/ceb90cb3afcb30e7c8a10a40851a03bc8295e056)
