### ISSUE TITLE
Add specific instructions for creating custom media

### ISSUE THREAD

**Issue by kelwyres** [kelwyres/Bactabolize#8]
Add instrcutsion to wiki
file format
need to place in spec directory etc
details of components that are supported - i.e. link to to teh pre-existing list as well as details of the components added by Ben

**Comment by bananabenana** [comment]
Resolved with https://github.com/kelwyres/Bactabolize/wiki/3.-Build-a-model#custom-medias and https://github.com/kelwyres/Bactabolize/wiki/4.-Predict-growth-profiles#custom-spec-files
